# chart-repo: argo/argo-cd
# chart-version: latest
# chart-ingress: true

server:
  extraArgs:
    - --insecure

ingress:
  enabled: INGRESS_ENABLED
  hosts:
    - INGRESS_DOMAIN
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

config:
  url: https://INGRESS_DOMAIN
  helmRepositories:
    - name: chartmuseum
      url: https://chartmuseum-devops.BASE_DOMAIN

rbac:
  policyDefault: role:readonly
