# chart-repo: stable/sonatype-nexus
# chart-version: latest
# chart-ingress: true
# chart-pvc: sonatype-nexus-data ReadWriteOnce 30Gi

nexus:
  # imageName: quay.io/travelaudience/docker-nexus
  serviceType: SERVICE_TYPE
  resources:
    requests:
      cpu: 200m
      memory: 3072Mi
    limits:
      cpu: 500m
      memory: 4096Mi
  livenessProbe:
    initialDelaySeconds: 200
    periodSeconds: 30
    failureThreshold: 12
    path: /
  readinessProbe:
    initialDelaySeconds: 200
    periodSeconds: 30
    failureThreshold: 12
    path: /

nexusProxy:
  # imageName: quay.io/travelaudience/docker-nexus-proxy
  env:
    nexusHttpHost: INGRESS_DOMAIN
    # nexusDockerHost: docker-INGRESS_DOMAIN

nexusBackup:
  nexusAdminPassword: PASSWORD

ingress:
  enabled: INGRESS_ENABLED
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageSize: 30Gi
  #:EFS:storageClass: "efs"
  existingClaim: sonatype-nexus-data
