# chart-version: latest

nameOverride: sonarqube

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - INGRESS_DOMAIN

resources:
  requests:
    cpu: 1000m
    memory: 3072Mi
  limits:
    cpu: 2000m
    memory: 5120Mi

readinessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  #:EFS:storageClass: "efs"

postgresql:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    #:EFS:storageClass: "efs"
