def label = "worker-${UUID.randomUUID().toString()}"
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "10"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "executor", image: "$EXECUTOR_IMAGE", command: "cat", ttyEnabled: true, alwaysPullImage: true),
  containerTemplate(name: "builder", image: "quay.io/nalbam/builder", command: "cat", ttyEnabled: true, alwaysPullImage: true),
  containerTemplate(name: "docker", image: "docker", command: "cat", ttyEnabled: true, alwaysPullImage: true)
], volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock"),
  hostPathVolume(mountPath: "/home/jenkins/.version", hostPath: "/home/jenkins/.version"),
  hostPathVolume(mountPath: "/home/jenkins/.helm", hostPath: "/home/jenkins/.helm")
]) {
  node(label) {
    stage("Checkout") {
      if (env.REPOSITORY_SECRET) {
        git(url: "$REPOSITORY_URL", branch: "$BRANCH", credentialsId: "$REPOSITORY_SECRET")
      } else {
        git(url: "$REPOSITORY_URL", branch: "$BRANCH")
      }
    }
    stage("Make Version") {
      container("builder") {
        sh """
          bash /root/extra/jenkins-domain.sh
          bash /root/extra/jenkins-version.sh $IMAGE_NAME $BRANCH
        """
      }
    }
    stage("Build") {
      container("executor") {
        sh """
          $BUILD
        """
      }
    }
    stage("Test") {
      container("executor") {
        sh """
          $TEST
        """
      }
    }
    stage("Result") {
      junit "**/target/surefire-reports/TEST-*.xml"
      archive "target/*.jar,target/*.war"
    }
    stage("Build Image") {
      container("docker") {
        def REGISTRY = readFile "/home/jenkins/REGISTRY"
        def VERSION = readFile "/home/jenkins/VERSION"
        sh """
          docker build -t $REGISTRY/$IMAGE_NAME:$VERSION .
          docker push $REGISTRY/$IMAGE_NAME:$VERSION
        """
      }
    }
  }
}
