# istio

ingress:
  enabled: true

grafana:
  enabled: true

kiali:
  enabled: true
  ingress:
    enabled: INGRESS_ENABLED
    hosts:
    - kiali.local
    - kiali-istio.BASE_DOMAIN
  dashboard:
    username: admin
    passphrase: PASSWORD
    grafanaURL: http://grafana:3000
    jaegerURL: https://jaeger-istio.BASE_DOMAIN

tracing:
  enabled: true
  ingress:
    enabled: INGRESS_ENABLED
    hosts:
    - tracing.local
    - tracing-istio.BASE_DOMAIN
  jaeger:
    ingress:
      enabled: INGRESS_ENABLED
      hosts:
      - jaeger.local
      - jaeger-istio.BASE_DOMAIN

servicegraph:
  enabled: true
  ingress:
    enabled: INGRESS_ENABLED
    hosts:
    - servicegraph.local
    - servicegraph-istio.BASE_DOMAIN
