# chart-repo: stable/external-dns
# chart-version: 1.6.0

nameOverride: external-dns

sources:
  - service
  # - ingress

aws:
  accessKey: AWS_ACCESS_KEY
  secretKey: AWS_SECRET_KEY

rbac:
  create: true
