# chart-repo: stable/nginx-ingress
# chart-version: latest

nameOverride: nginx-ingress

controller:
  replicaCount: 2
  # autoscaling:
  #   enabled: true
  #   minReplicas: 2
  #   maxReplicas: 9
  #   targetCPUUtilizationPercentage: 50
  #   targetMemoryUtilizationPercentage: 50
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    targetPorts:
      http: http
      https: http
