def label = "worker-${UUID.randomUUID().toString()}"
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "30"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "builder", image: "quay.io/nalbam/builder", command: "cat", ttyEnabled: true, alwaysPullImage: true)
], volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock"),
  hostPathVolume(mountPath: "/home/jenkins/.helm", hostPath: "/home/jenkins/.helm")
]) {
  node(label) {
    stage("Environment") {
      container("builder") {
        if (CLUSTER) {
          sh """
            /root/extra/secret.sh $REPOSITORY_SECRET .kube.config /root/.kube/config
          """
        }
      }
    }
    stage("Deploy Image") {
      container("builder") {
        sh """
          /root/extra/deploy.sh $IMAGE_NAME $VERSION $NAMESPACE
        """
      }
    }
  }
}
