apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
        version: master
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: CLEAN_PERIOD
              value: "{{ .Values.env.CLEAN_PERIOD }}"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: false
            - name: docker-dir
              mountPath: /var/lib/docker
              readOnly: false
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-dir
          hostPath:
            path: /var/lib/docker
