@Library("github.com/opsnow-tools/valve-butler")
def pump = new com.opsnow.valve.Butler()
def label = "worker-${UUID.randomUUID().toString()}"
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "30"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "builder", image: "opspresso/builder", command: "cat", ttyEnabled: true, alwaysPullImage: true)
], volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock"),
  hostPathVolume(mountPath: "/home/jenkins/.helm", hostPath: "/home/jenkins/.helm")
]) {
  node(label) {
    stage("Prepare") {
      container("builder") {
        pump.prepare()

        if (!SLACK_TOKEN) {
          SLACK_TOKEN = pump.slack_token
        }
      }
    }
    stage("Remove") {
      container("builder") {
        pump.helm_delete(IMAGE_NAME, NAMESPACE, CLUSTER)
        success(SLACK_TOKEN, "Remove", IMAGE_NAME, NAMESPACE, CLUSTER)
      }
    }
  }
}
def success(token = "", type = "", name = "", namespace = "", cluster = "") {
  if (cluster) {
    slack("$token", "warning", "$type Success", "`$name` :boom: `$namespace` :earth_asia: `$cluster`", "$JOB_NAME <$RUN_DISPLAY_URL|#$BUILD_NUMBER>")
  } else {
    slack("$token", "warning", "$type Success", "`$name` :boom: `$namespace`", "$JOB_NAME <$RUN_DISPLAY_URL|#$BUILD_NUMBER>")
  }
}
def slack(token = "", color = "", title = "", message = "", footer = "") {
  try {
    // pump.slack("$token", "$color", "$title", "$message", "$footer")
    sh """
      curl -sL toast.sh/helper/slack.sh | bash -s -- --token='$token' \
      --color='$color' --title='$title' --footer='$footer' '$message'
    """
  } catch (ignored) {
  }
}
