# nameOverride: jenkins

rbac:
  install: true

Persistence:
  Enabled: true
  AccessMode: ReadWriteOnce
  Size: 8Gi
  #:EFS:StorageClass: "efs"

# Agent:
#   Enabled: true
#   Image: quay.io/nalbam/jnlp-slave
#   ImageTag: latest
#   AlwaysPullImage: true

Master:
  # Image: quay.io/nalbam/jenkins
  # ImageTag: latest
  AdminUser: admin
  AdminPassword: password
  JavaOpts: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"
  ServiceType: SERVICE_TYPE
  HostName: INGRESS_DOMAIN
  # Ingress:
  #   ApiVersion: extensions/v1beta1
  #   kubernetes.io/ingress.class: nginx
  #   TLS:
  #   - secretName: INGRESS_DOMAIN
  #     hosts:
  #       - INGRESS_DOMAIN
  InstallPlugins:
    - blueocean:latest
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - kubernetes-credentials-provider:latest
    - pipeline-github-lib:latest
    - script-security:1.44
  # Jobs: -- auto generate -- see: jobs/replace.sh
