# chart-version: latest

# nexus:
#   serviceType: SERVICE_TYPE

nexusProxy:
  env:
    nexusHttpHost: INGRESS_DOMAIN
    nexusDockerHost: docker-INGRESS_DOMAIN

ingress:
  enabled: INGRESS_ENABLED
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageSize: 10Gi
  #:EFS:storageClass: "efs"

resources:
  requests:
    cpu: 1000m
    memory: 4800Mi
