# chart-version: latest

nexus:
  # imageName: quay.io/travelaudience/docker-nexus
  # imageTag: 3.13.0
  serviceType: SERVICE_TYPE
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 6
    path: /
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 6
    path: /

nexusProxy:
  # imageName: quay.io/travelaudience/docker-nexus-proxy
  # imageTag: 2.3.0
  env:
    nexusHttpHost: INGRESS_DOMAIN
    nexusDockerHost: docker-INGRESS_DOMAIN

ingress:
  enabled: INGRESS_ENABLED
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageSize: 30Gi
  #:EFS:storageClass: "efs"

resources:
  requests:
    cpu: 1000m
    memory: 4800Mi
