nexusProxy:
  env:
    nexusHttpHost: ingress.domain.com
    nexusDockerHost: docker-ingress.domain.com
ingress:
  enabled: true
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m
