# chart-version: latest

nameOverride: sonarqube

# service:
#   type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - INGRESS_DOMAIN

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  #:EFS:storageClass: "efs"

postgresql:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    #:EFS:storageClass: "efs"
