# chart-repo: custom/elasticsearch-snapshot
# chart-version: latest

image:
  repository: opsnowtools/elasticsearch-snapshot
  tag: latest

schedule: "SCHEDULE"

restart: RESTART

secret:
  enabled: true
