@Library("github.com/opsnow-tools/valve-butler")
def butler = new com.opsnow.valve.v7.Butler()
def label = "worker-${UUID.randomUUID().toString()}"
def IMAGE_NAME = "${SERVICE_GROUP}-${SERVICE_NAME}"
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "30"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "builder", image: "quay.io/opsnow-tools/valve-builder", command: "cat", ttyEnabled: true, alwaysPullImage: true)
], volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock"),
  hostPathVolume(mountPath: "/home/jenkins/.helm", hostPath: "/home/jenkins/.helm")
]) {
  node(label) {
    stage("Prepare") {
      container("builder") {
        butler.prepare(IMAGE_NAME)
      }
    }
    stage("Checkout") {
      container("builder") {
        try {
          if (REPOSITORY_SECRET) {
            git(url: REPOSITORY_URL, branch: BRANCH_NAME, credentialsId: REPOSITORY_SECRET)
          } else {
            git(url: REPOSITORY_URL, branch: BRANCH_NAME)
          }
        } catch (e) {
          butler.failure(SLACK_TOKEN, "Checkout")
          throw e
        }
      }
    }
    stage("Build Image") {
      parallel(
        "Build Docker": {
          container("builder") {
            try {
              butler.build_image()
            } catch (e) {
              butler.failure(SLACK_TOKEN, "Build Docker")
              throw e
            }
          }
        },
        "Build Charts": {
          container("builder") {
            try {
              butler.build_chart()
            } catch (e) {
              butler.failure(SLACK_TOKEN, "Build Charts")
              throw e
            }
          }
        }
      )
    }
  }
}
