# chart-repo: httpbin
# chart-version: latest
# chart-ingress: true

pod:
  labels:
    spotinst.io/pods-contingency: "true"
    spotinst.io/restrict-scale-down: "true"

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  basedomain: BASE_DOMAIN
