# chart-repo: sample-web
# chart-version: latest
# chart-ingress: true

profile: dev

image:
  repository: nalbam/sample-web
  tag: alpine

pod:
  labels:
    spotinst.io/pods-contingency: "true"
    spotinst.io/restrict-scale-down: "true"

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  basedomain: BASE_DOMAIN
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

configmap:
  enabled: false
secret:
  enabled: false
