# chart-repo: sample-webpack
# chart-version: latest
# chart-ingress: true

profile: dev

image:
  repository: nalbam/sample-webpack
  tag: alpine

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  basedomain: BASE_DOMAIN
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
