# chart-repo: sample-node
# chart-version: latest
# chart-ingress: true

profile: dev

image:
  repository: nalbam/sample-node
  tag: alpine

pod:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

pdb:
  #minAvailable: 1
  maxUnavailable: 1

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  basedomain: BASE_DOMAIN
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

configmap:
  enabled: false
secret:
  enabled: false
