# chart-repo: sample-spring
# chart-version: latest
# chart-ingress: true

profile: default

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  basedomain: BASE_DOMAIN

configmap:
  enabled: CONFIGMAP_ENABLED

secret:
  enabled: SECRET_ENABLED

istio:
  enabled: ISTIO_ENABLED

canary:
  enabled: false
  tag: alpine
