# chart-repo: sample-web
# chart-version: latest
# chart-ingress: true

profile: dev

image:
  repository: nalbam/sample-web
  tag: alpine

pod:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  basedomain: BASE_DOMAIN
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

hpa:
  enabled: true
  min: 20
  max: 30
  cpu: 65

configmap:
  enabled: false
secret:
  enabled: false
