@Library('github.com/opspresso/pipeline@master')
def pipeline = new com.opspresso.Pipeline()
def label = "worker-${UUID.randomUUID().toString()}"
def VERSION = ""
def SOURCE_LANG = ""
def SOURCE_ROOT = ""
def BASE_DOMAIN = ""
def REGISTRY = ""
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "30"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "builder", image: "quay.io/opspresso/builder", command: "cat", ttyEnabled: true, alwaysPullImage: true),
  containerTemplate(name: "maven", image: "maven", command: "cat", ttyEnabled: true),
  containerTemplate(name: "node", image: "node", command: "cat", ttyEnabled: true)
], volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock"),
  hostPathVolume(mountPath: "/home/jenkins/.draft", hostPath: "/home/jenkins/.draft"),
  hostPathVolume(mountPath: "/home/jenkins/.helm", hostPath: "/home/jenkins/.helm")
]) {
  node(label) {
    stage("Checkout") {
      container("builder") {
        try {
          if (REPOSITORY_SECRET) {
            git(url: REPOSITORY_URL, branch: BRANCH_NAME, credentialsId: REPOSITORY_SECRET)
          } else {
            git(url: REPOSITORY_URL, branch: BRANCH_NAME)
          }
        } catch (e) {
          checkout_failure(IMAGE_NAME, RUN_DISPLAY_URL)
          throw e
        }

        pipeline.scan(IMAGE_NAME, BRANCH_NAME)

        VERSION = pipeline.version
        SOURCE_LANG = pipeline.source_lang
        SOURCE_ROOT = pipeline.source_root
        BASE_DOMAIN = pipeline.base_domain
        REGISTRY = pipeline.registry

        if (!SLACK_TOKEN) {
          SLACK_TOKEN = pipeline.slack_token
        }
      }
    }
    stage("Build") {
      if (SOURCE_LANG == "java") {
        container("maven") {
          try {
            sh """
              cd $SOURCE_ROOT
              mvn package -s /home/jenkins/.m2/settings.xml
            """
            build_success(IMAGE_NAME, VERSION, RUN_DISPLAY_URL)
          } catch (e) {
            build_failure(IMAGE_NAME, RUN_DISPLAY_URL)
            throw e
          }
        }
      }
      else if (SOURCE_LANG == "nodejs") {
        container("node") {
          try {
            sh """
              cd $SOURCE_ROOT
              npm run build
            """
            build_success(IMAGE_NAME, VERSION, RUN_DISPLAY_URL)
          } catch (e) {
            build_failure(IMAGE_NAME, RUN_DISPLAY_URL)
            throw e
          }
        }
      }
      else {
        sh """
          echo "skipped."
        """
      }
    }
    if (BRANCH_NAME != "master") {
      stage("Development") {
        container("builder") {
          pipeline.draft_up(IMAGE_NAME, "development", CLUSTER, BASE_DOMAIN)
          deploy_success(IMAGE_NAME, VERSION, "development", BASE_DOMAIN)
        }
      }
    }
    if (BRANCH_NAME == "master") {
      stage("Build Image") {
        parallel(
          "Build Docker": {
            container("builder") {
              pipeline.build_image(IMAGE_NAME, VERSION)
            }
          },
          "Build Charts": {
            container("builder") {
              pipeline.build_chart(IMAGE_NAME, VERSION)
            }
          }
        )
      }
      stage("Staging") {
        container("builder") {
          pipeline.helm_install(IMAGE_NAME, VERSION, "staging", CLUSTER, BASE_DOMAIN)
          deploy_success(IMAGE_NAME, VERSION, "staging", BASE_DOMAIN)
        }
      }
      stage("Confirm") {
        container("builder") {
          deploy_confirm(IMAGE_NAME, VERSION, "production", RUN_DISPLAY_URL)
          timeout(time: 60, unit: "MINUTES") {
            input(message: "$IMAGE_NAME $VERSION to production")
          }
        }
      }
      stage("Production") {
        container("builder") {
          pipeline.helm_install(IMAGE_NAME, VERSION, "production", CLUSTER, BASE_DOMAIN)
          deploy_success(IMAGE_NAME, VERSION, "production", BASE_DOMAIN)
        }
      }
    }
  }
}
def checkout_failure(IMAGE_NAME, RUN_DISPLAY_URL) {
  notify("danger", "Checkout Failure", "`$IMAGE_NAME`", "$JOB_NAME <$RUN_DISPLAY_URL|#$BUILD_NUMBER>")
}
def build_failure(IMAGE_NAME, RUN_DISPLAY_URL) {
  notify("danger", "Build Failure", "`$IMAGE_NAME`", "$JOB_NAME <$RUN_DISPLAY_URL|#$BUILD_NUMBER>")
}
def build_success(IMAGE_NAME, VERSION, RUN_DISPLAY_URL) {
  notify("good", "Build Success", "`$IMAGE_NAME` `$VERSION` :heavy_check_mark:", "$JOB_NAME <$RUN_DISPLAY_URL|#$BUILD_NUMBER>")
}
def deploy_confirm(IMAGE_NAME, VERSION, NAMESPACE, RUN_DISPLAY_URL) {
  notify("warning", "Deply Confirm", "`$IMAGE_NAME` `$VERSION` :rocket: `$NAMESPACE`", "$JOB_NAME <$RUN_DISPLAY_URL|#$BUILD_NUMBER>")
}
def deploy_success(IMAGE_NAME, VERSION, NAMESPACE, BASE_DOMAIN) {
  def LINK="https://$IMAGE_NAME-$NAMESPACE.$BASE_DOMAIN"
  notify("good", "Deply Success", "`$IMAGE_NAME` `$VERSION` :satellite: `$NAMESPACE`", "see <$LINK|$IMAGE_NAME-$NAMESPACE>")
}
def notify(COLOR, TITLE, MESSAGE, FOOTER) {
  pipeline.notify(SLACK_TOKEN, COLOR, TITLE, MESSAGE, FOOTER)
}
