# chart-repo: stable/fluentd-elasticsearch
# chart-version: latest

nameOverride: fluentd-elasticsearch

elasticsearch:
  host: CUSTOM_HOST
  port: CUSTOM_PORT
  buffer_chunk_limit: 2M
  buffer_queue_limit: 8
