# chart-repo: stable/prometheus
# chart-version: 8.8.1
# chart-ingress: false
# chart-pvc: prometheus-server ReadWriteOnce 8Gi
# chart-pvc: prometheus-alertmanager ReadWriteOnce 2Gi

nameOverride: prometheus

server:
  #:ING:service:
  #:ING:  type: SERVICE_TYPE
  #:ING:ingress:
  #:ING:  enabled: INGRESS_ENABLED
  #:ING:  annotations:
  #:ING:    kubernetes.io/ingress.class: nginx
  #:ING:    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #:ING:  hosts:
  #:ING:    - INGRESS_DOMAIN
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    #:EFS:storageClass: "efs"
    existingClaim: prometheus-server

alertmanager:
  #:ING:service:
  #:ING:  type: SERVICE_TYPE
  #:ING:ingress:
  #:ING:  enabled: INGRESS_ENABLED
  #:ING:  annotations:
  #:ING:    kubernetes.io/ingress.class: nginx
  #:ING:    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #:ING:  hosts:
  #:ING:    - alertmanager-INGRESS_DOMAIN
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    #:EFS:storageClass: "efs"
    existingClaim: prometheus-alertmanager
