# chart-repo: stable/prometheus-operator
# chart-version: 2.1.0
# chart-ingress: true

nameOverride: prometheus-operator

alertmanager:
  enabled: true
  ingress:
    enabled: INGRESS_ENABLED
    hosts:
    - alertmanager-INGRESS_DOMAIN

grafana:
  enabled: true
  ingress:
    enabled: INGRESS_ENABLED
    hosts:
    - grafana-INGRESS_DOMAIN
