@Library("github.com/opsnow-tools/valve-pump")
def pump = new com.opsnow.valve.Pump()
def label = "worker-${UUID.randomUUID().toString()}"
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "30"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "builder", image: "opspresso/builder", command: "cat", ttyEnabled: true, alwaysPullImage: true)
], volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock"),
  hostPathVolume(mountPath: "/home/jenkins/.draft", hostPath: "/home/jenkins/.draft"),
  hostPathVolume(mountPath: "/home/jenkins/.helm", hostPath: "/home/jenkins/.helm")
]) {
  node(label) {
    stage("Info") {
      sh """
        pwd
        date
        whoami
        uname -a
        echo $JOB_NAME
        echo $BUILD_NUMBER
      """
    }
    stage("Prepare") {
      container("builder") {
        sh """
          pwd
          date
          whoami
          uname -a
        """
        pump.prepare()
      }

      pump.scan("sample")
    }
    stage("Run docker") {
      container("builder") {
        sh """
          docker version
          docker images
          docker ps
        """
      }
    }
    stage("Run kubectl") {
      container("builder") {
        sh """
          kubectl version
          kubectl cluster-info
          kubectl get pod,svc,ing
        """
      }
    }
    stage("Run helm") {
      container("builder") {
        pump.helm_init()
      }
    }
    stage("Run draft") {
      container("builder") {
        pump.draft_init()
      }
    }
    stage("End") {
      container("builder") {
        sh """
          ls -al
        """
      }
    }
  }
}
