def label = "worker-${UUID.randomUUID().toString()}"
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "30"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "builder", image: "quay.io/nalbam/builder", command: "cat", ttyEnabled: true, alwaysPullImage: true),
  containerTemplate(name: "docker", image: "docker", command: "cat", ttyEnabled: true)
], volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock"),
  hostPathVolume(mountPath: "/home/jenkins/.draft", hostPath: "/home/jenkins/.draft"),
  hostPathVolume(mountPath: "/home/jenkins/.helm", hostPath: "/home/jenkins/.helm")
]) {
  node(label) {
    stage("Info") {
      sh """
        pwd
        date
        uname -a
        echo $JOB_NAME
        echo $BUILD_NUMBER
      """
    }
    stage("Prepare") {
      container("builder") {
        sh """
          pwd
          date
          uname -a
          /root/extra/prepare.sh
          /root/extra/detect.sh
          ls -al /home/jenkins
        """
      }
    }
    stage("Run") {
      parallel(
        "Run docker": {
          container("docker") {
            sh """
              docker version
              docker images
              docker ps
            """
          }
        },
        "Run kubectl": {
          container("builder") {
            sh """
              kubectl version --client --short
              kubectl cluster-info
              kubectl get pod,svc,ing
            """
          }
        },
        "Run helm": {
          container("builder") {
            sh """
              /root/extra/helm-init.sh
            """
          }
        },
        "Run draft": {
          stage("Run draft") {
            container("builder") {
              sh """
                /root/extra/draft-init.sh
              """
            }
          }
        }
      )
    }
  }
}
