apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: helm
    name: tiller
  name: PDB_NAME
spec:
  #:MIN:minAvailable: PDB_MIN
  #:MAX:maxUnavailable: PDB_MAX
  selector:
    matchLabels:
      app: helm
      name: tiller
