{{ if (not (empty .Values.istio)) }}
{{ if (.Values.istio.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  hosts:
    - {{ template "fullname" . }}
  http:
  - route:
    - destination:
        host: {{ template "fullname" . }}
        subset: master
{{ end }}
{{ end }}
